<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[HomePage_test==== Execution Started ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution onTestSkipped Skipped ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution Started ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution onTestSkipped Skipped ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution Started ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
    </line>
  </reporter-output>
  <suite started-at="2024-08-01T19:24:18 IST" name="Default suite" finished-at="2024-08-01T19:25:29 IST" duration-ms="70896">
    <groups>
    </groups>
    <test started-at="2024-08-01T19:24:18 IST" name="Default test" finished-at="2024-08-01T19:25:29 IST" duration-ms="70896">
      <class name="com.BusinessLogic.TestCase1">
        <test-method is-config="true" signature="Config_bc(java.lang.String)[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:24:19 IST" name="Config_bc" finished-at="2024-08-01T19:24:25 IST" duration-ms="5804" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Config_bc -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:24:25 IST" name="loginSetup" finished-at="2024-08-01T19:24:27 IST" duration-ms="2661" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method retried="true" signature="HomePage_test()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:24:27 IST" name="HomePage_test" finished-at="2024-08-01T19:24:46 IST" duration-ms="18882" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.BusinessLogic.TestCase1.HomePage_test(TestCase1.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HomePage_test==== Execution Started ]]>
            </line>
            <line>
              <![CDATA[HomePage_test==== Execution onTestSkipped Skipped ]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomePage_test -->
        <test-method is-config="true" signature="appShutdown()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:24:46 IST" name="appShutdown" finished-at="2024-08-01T19:24:47 IST" duration-ms="1034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appShutdown -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:24:47 IST" name="loginSetup" finished-at="2024-08-01T19:24:48 IST" duration-ms="776" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method retried="true" signature="HomePage_test()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:24:48 IST" name="HomePage_test" finished-at="2024-08-01T19:25:07 IST" duration-ms="18715" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.BusinessLogic.TestCase1.HomePage_test(TestCase1.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HomePage_test==== Execution Started ]]>
            </line>
            <line>
              <![CDATA[HomePage_test==== Execution onTestSkipped Skipped ]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomePage_test -->
        <test-method is-config="true" signature="appShutdown()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:25:07 IST" name="appShutdown" finished-at="2024-08-01T19:25:07 IST" duration-ms="782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appShutdown -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:25:07 IST" name="loginSetup" finished-at="2024-08-01T19:25:08 IST" duration-ms="834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method signature="HomePage_test()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:25:08 IST" name="HomePage_test" finished-at="2024-08-01T19:25:28 IST" duration-ms="19315" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.BusinessLogic.TestCase1.HomePage_test(TestCase1.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HomePage_test==== Execution Started ]]>
            </line>
            <line>
              <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomePage_test -->
        <test-method is-config="true" signature="appShutdown()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:25:28 IST" name="appShutdown" finished-at="2024-08-01T19:25:29 IST" duration-ms="1258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appShutdown -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:com.BusinessLogic.TestCase1@5ddeb7cb]" started-at="2024-08-01T19:25:29 IST" name="Teardown" finished-at="2024-08-01T19:25:29 IST" duration-ms="309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- com.BusinessLogic.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
